cp -R GA_fort/* GA_fort1/ 
cp -R GA_fort/* GA_fort2/ 
cp -R GA_fort/* GA_fort3/ 
cp -R GA_fort/* GA_fort4/ 
cp -R GA_fort/* GA_fort5/ 
cp -R GA_fort/* GA_fort6/ 
cp -R GA_fort/* GA_fort7/ 
cp -R GA_fort/* GA_fort8/ 
cp -R GA_fort/* GA_fort9/ 
cp -R GA_fort/* GA_fort10/ 
cp -R GA_fort/* GA_fort11/ 
cp -R GA_fort/* GA_fort12/ 
cp -R GA_fort/* GA_fort13/ 
cp -R GA_fort/* GA_fort14/ 
cp -R GA_fort/* GA_fort15/ 
cp -R GA_fort/* GA_fort16/ 
cp -R GA_fort/* GA_fort17/ 
cp -R GA_fort/* GA_fort18/ 
cp -R GA_fort/* GA_fort19/ 
cp -R GA_fort/* GA_fort20/ 
cp -R GA_fort/* GA_fort21/ 
cp -R GA_fort/* GA_fort22/ 
cp -R GA_fort/* GA_fort23/ 
cp -R GA_fort/* GA_fort24/ 
cp -R GA_fort/* GA_fort25/ 
cp -R GA_fort/* GA_fort26/ 
cp -R GA_fort/* GA_fort27/ 
cp -R GA_fort/* GA_fort28/ 
cp -R GA_fort/* GA_fort29/ 
cp -R GA_fort/* GA_fort30/ 
cp -R GA_fort/* GA_fort31/ 
cp -R GA_fort/* GA_fort32/ 
cp -R GA_fort/* GA_fort33/ 
cp -R GA_fort/* GA_fort34/ 
cp -R GA_fort/* GA_fort35/ 
cp -R GA_fort/* GA_fort36/ 
cp -R GA_fort/* GA_fort37/ 
cp -R GA_fort/* GA_fort38/ 
cp -R GA_fort/* GA_fort39/ 
cp -R GA_fort/* GA_fort40/ 
cp -R GA_fort/* GA_fort41/ 
cp -R GA_fort/* GA_fort42/ 
cp -R GA_fort/* GA_fort43/ 
cp -R GA_fort/* GA_fort44/ 
cp -R GA_fort/* GA_fort45/ 
cp -R GA_fort/* GA_fort46/ 
cp -R GA_fort/* GA_fort47/ 
cp -R GA_fort/* GA_fort48/ 
cp -R GA_fort/* GA_fort49/ 
cp -R GA_fort/* GA_fort50/ 
cp -R GA_fort/* GA_fort51/ 
cp -R GA_fort/* GA_fort52/ 
cp -R GA_fort/* GA_fort53/ 
cp -R GA_fort/* GA_fort54/ 
cp -R GA_fort/* GA_fort55/ 
cp -R GA_fort/* GA_fort56/ 
cp -R GA_fort/* GA_fort57/ 
cp -R GA_fort/* GA_fort58/ 
cp -R GA_fort/* GA_fort59/ 
cp -R GA_fort/* GA_fort60/ 
cp -R GA_fort/* GA_fort61/ 
cp -R GA_fort/* GA_fort62/ 
cp -R GA_fort/* GA_fort63/ 
cp -R GA_fort/* GA_fort64/ 
cp -R GA_fort/* GA_fort65/ 
cp -R GA_fort/* GA_fort66/ 
cp -R GA_fort/* GA_fort67/ 
cp -R GA_fort/* GA_fort68/ 
cp -R GA_fort/* GA_fort69/ 
cp -R GA_fort/* GA_fort70/ 
cp -R GA_fort/* GA_fort71/ 
cp -R GA_fort/* GA_fort72/ 
cp -R GA_fort/* GA_fort73/ 
cp -R GA_fort/* GA_fort74/ 
cp -R GA_fort/* GA_fort75/ 
cp -R GA_fort/* GA_fort76/ 
cp -R GA_fort/* GA_fort77/ 
cp -R GA_fort/* GA_fort78/ 
cp -R GA_fort/* GA_fort79/ 
cp -R GA_fort/* GA_fort80/ 
cp -R GA_fort/* GA_fort81/ 
cp -R GA_fort/* GA_fort82/ 
cp -R GA_fort/* GA_fort83/ 
cp -R GA_fort/* GA_fort84/ 
cp -R GA_fort/* GA_fort85/ 
cp -R GA_fort/* GA_fort86/ 
cp -R GA_fort/* GA_fort87/ 
cp -R GA_fort/* GA_fort88/ 
cp -R GA_fort/* GA_fort89/ 
cp -R GA_fort/* GA_fort90/ 
cp -R GA_fort/* GA_fort91/ 
cp -R GA_fort/* GA_fort92/ 
cp -R GA_fort/* GA_fort93/ 
cp -R GA_fort/* GA_fort94/ 
cp -R GA_fort/* GA_fort95/ 
cp -R GA_fort/* GA_fort96/ 
cp -R GA_fort/* GA_fort97/ 
cp -R GA_fort/* GA_fort98/ 
cp -R GA_fort/* GA_fort99/ 
cp -R GA_fort/* GA_fort100/ 
