cat empty.txt >> output.txt 
 cat GA_fort1/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort2/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort3/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort4/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort5/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort6/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort7/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort8/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort9/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort10/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort11/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort12/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort13/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort14/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort15/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort16/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort17/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort18/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort19/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort20/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort21/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort22/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort23/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort24/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort25/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort26/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort27/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort28/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort29/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort30/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort31/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort32/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort33/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort34/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort35/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort36/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort37/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort38/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort39/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort40/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort41/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort42/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort43/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort44/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort45/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort46/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort47/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort48/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort49/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort50/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort51/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort52/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort53/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort54/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort55/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort56/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort57/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort58/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort59/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort60/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort61/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort62/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort63/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort64/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort65/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort66/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort67/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort68/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort69/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort70/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort71/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort72/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort73/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort74/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort75/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort76/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort77/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort78/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort79/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort80/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort81/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort82/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort83/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort84/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort85/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort86/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort87/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort88/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort89/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort90/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort91/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort92/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort93/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort94/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort95/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort96/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort97/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort98/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort99/ga_out.txt >> output.txt
cat empty.txt >> output.txt 
 cat GA_fort100/ga_out.txt >> output.txt
